import type { NextPage } from "next";
import Head from "next/head";
import ForCanvas from "../components/ForCanvas";
import MobileViewText from "../components/MobileView";
import styles from "../styles/Home.module.css";
import { isMobile } from "react-device-detect";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello World</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { !isMobile ? (
        <main className={styles.main}>
          <ForCanvas />
        </main>
      ) : (
        <MobileViewText />
      ) }
    </div>
  );
};

export default Home;
